%%{init: { "fontFamily": "Source Code Pro" } }%%

flowchart TB

classDef I fill:#E49865,stroke:#333,stroke-width:2px;
classDef II fill:#EACEC5,stroke:#333,stroke-width:2px;
classDef III fill:#CBD6D5,stroke:#333,stroke-width:2px;
classDef IIII fill:#8CB4C3,stroke:#333,stroke-width:2px;

tdr([tabular-data-resource]):::I

name(name):::II
path(path):::II
version(version):::II   
schema([schema]):::II
title(title):::II
homepage(homepage):::II
description(description):::II

tdr --- name
tdr --- path
tdr --- version   
tdr --- title
tdr --- description
tdr --- homepage
tdr --- schema

schema --- fields([fields]):::III
schema --- primaryKey(primaryKey):::III
schema --- foreignKey(foreignKey):::III

fields --- field_name_1(field_1:\nname \n title \n description \n type):::IIII
fields --- field_name_2(field_2:\nname \n title \n type \n constraints):::IIII
fields --- field_name_3(field_3:\nname \n title \n description \n type \n constraints):::IIII
