flowchart TB

classDef I fill:#E49865,stroke:#333,stroke-width:2px;
classDef II fill:#EACEC5,stroke:#,stroke-width:2px;
classDef III fill:#CBD6D5,stroke:#333,stroke-width:2px;
classDef IIII fill:#8CB4C3,stroke:#333,stroke-width:2px;
classDef IV fill:#F6EDDE,stroke:#333,stroke-width:2px;

tdr([tabular-data-resource \n descriptors]):::I

name(name):::II
path(path):::II
title(title):::II
description(description):::II
url(url):::II
license(license):::II
schema(schema):::II

tdr ---- schema

tdr ---- name
tdr ---- path
tdr ---- title
tdr ---- description
tdr ---- url
tdr ---- license

schema --- fields(fields):::III
schema --- missingValues(missingValues):::III
schema --- primaryKey(primaryKey):::III
schema --- foreignKey(foreignKey):::III

fields --- field_name_1{{**field_1** \n name \n title \n description \n type}}:::IIII
fields --- field_name_2{{name \n title \n type \n constraints}}:::IIII
fields --- field_name_3{{name \n title \n description \n type \n constraints}}:::IIII
