---
title: "CODEC Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CODEC Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## CODEC Data Standards

> *Language:* The keywords “MUST”, “MUST NOT”, “SHOULD”, “SHOULD NOT”, and “MAY” in this document are to be interpreted as described in [RFC 2119](https://tools.ietf.org/html/rfc2119).

### File Formats

A CODEC `tabular-data-resource` (i.e., `tdr`) consists of a directory that MUST contain exactly one data (`.csv`) file and exactly one metadata file (`tabular-data-resource.yaml`). The name of the directory and the name of the CSV file containing the data MUST be identical to the `name` [*property*](codec-metadata.html#tabular-data-resource-metadata).

For example,

    mydata
    ├── mydata.csv
    └── tabular-data-resource.yaml

#### Metadata file

The metadata file MUST be a valid YAML file named `tabular-data-resource.yaml` and it MUST adhere to the [CODEC Metadata Standards](codec-metadata.html#codec-metadata-specifications).

#### Data file

The data file must follow the [RFC 4180](https://www.rfc-editor.org/rfc/rfc4180) standard for CSV files.  In addition:

- the filename must end with `.csv`
- the first row MUST be a header row, containing the `name` of each *field*
- each `name` must be unique among all fields
  
#### For both files:

- the file encoding MUST be UTF-8
- newlines MUST be encoded with either `\n` or `\r\n`
- the newline style SHOULD be consistent within a file
- there SHOULD be a newline at the end of the file

All fields in the data MUST be described in the metadata.  All fields described in the metadata MUST be in the data.

### Missing Values

If a value is missing, it MUST be represented by either `NA` or an empty string (``) in the CSV data file.

### Census Tract Geography

A [census tract](https://www2.census.gov/geo/pdfs/education/CensusTracts.pdf) column MUST be specified in metadata and named `census_tract_id_{year}`, where `{year}` is replaced with the decennial vintage of the census tract geographies used to create the dataset (e.g., `census_tract_id_2010` or `census_tract_id_2020`).

The census tract identifier column MUST contain 11-digit [GEOID](https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html) identifiers for *all* census tracts in Hamilton County (GEOID: 39061). A list of required census tract identifiers for 2000, 2010, and 2020 are available in the {{[cincy](https://github.com/geomarker-io/cincy)}} R package (e.g., `cincy::tract_tigris_2010`).

A CODEC `tdr` that was *not* created at a census tract level SHOULD link to a URL that contains code and a descriptive README file about how the data was harmonized (e.g., areal interpolation) with census tract geographies.


### Date // Date Range??

- data must correspond to a year or month
- *or* require start_date and end_date and assume value represents temporal average of this time period

### Data Location

- AWS Simple Storage Service (S3) is a cloud-based centralized storage area and CODEC data are located in a public bucket: [`s3://codec-data/`](https://codec-data.s3.amazonaws.com/)
  - [bucket versioning](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html) is used to create unique identifiers for each version of a data resource
