---
title: "Hamilton County Census Tract-Level Neighborhood Indices"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Hamilton County Census Tract-Level Neighborhood Indices}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(CODECtools)
library(knitr)
options(knitr.kable.NA = '')
mapview::mapviewOptions(leafletWidth = 850)
```

```{r, include = FALSE}
name <- "tract_indices"
version <- gh::gh(glue::glue("/repos/geomarker-io/{name}/releases"))[[1]]$tag

d <- read_tdr_csv(glue::glue("https://github.com/geomarker-io/{name}/releases/download/{version}/")) |>
  dplyr::filter(substr(census_tract_id, 1, 5) == "39061") |>
  dplyr::rename(census_tract_id_2010 = census_tract_id) |>
  dplyr::mutate(year = as.integer(2019)) |>
  add_col_attrs(year, name = "year", title = "Year", description = "data year") |>
  add_type_attrs()

write_tdr_csv(d, dir = "tmp")
check_codec_tdr_csv(fs::dir_ls("tmp"))
fs::dir_delete("tmp")
write_tdr_csv(d, "codec_data/")
```

**last updated:** `r gh::gh(glue::glue("/repos/geomarker-io/{name}/releases"))[[1]]$created_at`

### Attributes

```{r, echo = FALSE}
attr(d, which = "version") <- glue::glue("[{attr(d, which = 'version')}](https://github.com/geomarker-io/{name}/releases)")
glimpse_attr(d) |>
  knitr::kable()
```

### Schema

```{r, echo = FALSE}
glimpse_schema(d) |>
  knitr::kable()
```

### Data

```{r, echo = FALSE}
DT::datatable(d, 
              extensions = 'Buttons', 
              options = list(
                dom = 'Bfrtip',
                buttons = 'csv', 
                scrollX = TRUE)
)
```

### Map

```{r, echo = FALSE, message = FALSE}
library(sf)

d <- dplyr::left_join(d, 
                      cincy::tract_tigris_2010, 
                      by = "census_tract_id_2010") |>
  st_as_sf()

m <- mapview::mapview(d, zcol = colnames(d)[2:(ncol(d)-1)]) 

m@map |>
  leaflet::hideGroup(colnames(d)[3:(ncol(d)-1)])
```


