#' geocode with degauss
#'
#' Calls docker to geocode using ghcr.io/degauss-org/geocoder:3.3.0
#' @details The working directory is used for the cache files generated by
#' DeGAUSS for individual address inputs, speeding up subsequent geocoding
#' calls for the same address in the future
#' @source https://degauss.org/geocoder
#' @param x character vector of addresses to geocode
#' @param work_dir path to folder to use for DeGAUSS geocoding cache
#' @return tibble with columns for address (`x`), geocode result, matched street, matched zip, lat, lon
#' @export
geocode_degauss <- function(
  x,
  work_dir = tools::R_user_dir("degauss", "cache")
) {
  degauss_folder <- fs::path(work_dir)
  fs::dir_create(degauss_folder)
  tmp_in <- fs::path(degauss_folder, rlang::hash(x), ext = "csv")
  readr::write_csv(tibble::tibble(address = x), tmp_in)
  system2(
    "docker",
    c(
      "run",
      "--rm",
      glue::glue("-v {degauss_folder}:/tmp"),
      ifelse(
        Sys.info()["machine"] == "arm64", # use alt tag for m1/m2 macs
        "ghcr.io/degauss-org/geocoder:3.3.0-v8",
        "ghcr.io/degauss-org/geocoder:3.3.0"
      ),
      fs::path_file(tmp_in)
    )
  )
  degauss_output <-
    readr::read_csv(
      fs::path(
        fs::path_dir(tmp_in),
        glue::glue("{rlang::hash(x)}_geocoder_3.3.0_score_threshold_0.5.csv")
      ),
      col_types = readr::cols_only(
        address = readr::col_character(),
        geocode_result = readr::col_character(),
        score = readr::col_double(),
        precision = readr::col_character(),
        matched_street = readr::col_character(),
        matched_zip = readr::col_character(),
        lat = readr::col_double(),
        lon = readr::col_double(),
      )
    )
  d_out <- dplyr::left_join(
    tibble::tibble(address = x),
    unique(degauss_output),
    by = "address"
  )
  return(d_out)
}
