%%{init: { "fontFamily": "arial" } }%%

flowchart LR

classDef I fill:#E49865,stroke:#333,stroke-width:1px;
classDef II fill:#EACEC5,stroke:#333,stroke-width:1px;
classDef III fill:#CBD6D5,stroke:#333,stroke-width:1px;
classDef IIII fill:#8CB4C3,stroke:#333,stroke-width:1px;
classDef V fill:#396175,color:#F6EAD8,stroke:#333,stroke-width:1px;


subgraph organization-data ["Organizational Data Silos"]
org[(community)]:::I
jfs[(government)]:::I
cchmc[(healthcare)]:::I
end
class organization-data II

auto[["automated interpolation \n and ingestion tools"]]:::IIII
auto --"CoDEC Standards"--> d

degauss[["decentralized geocoding \nand spatiotemporal \naggregation tools"]]:::III
acs("built, natural, \nand social environment"):::I
acs --> auto

org & jfs & cchmc -..-> auto

subgraph codec-box ["CoDEC"]
  d[("CoDEC harmonized \ndata packages")]:::IIII
  d <--> api((data API)):::IIII
  api --> data-catalog("interactive data \ncatalog (explore, map, \nassociate, download)"):::V
end
class codec-box III

api <-.-> c2d2("Other data catalogs \n(e.g., C2D2)"):::V
api <-..-> external("External integrations \n (e.g., PowerBI)"):::V

api --> publisher("QI analyst Research \nbiostat/epi \nCommunity scientist"):::II --SALT--> dashboard("dashboards, reports,\n scientific studies, \nintervention evaluation"):::V

