---
title: "Codec Shinyapps.io Hosting READme"
format: html
editor: visual
---

## Shinyapps.io Credentials

From the [shinyapps.io dashboard](https://login.shinyapps.io/login), retrieve your token and secret from the 'Account' tab on the left. Save these locally how you best see fit.

## Launch Code

Install the package [{rsconnect}](https://rstudio.github.io/rsconnect/). Navigate to the folder containing either your `app.R` or separate `ui.R` and `server.R` files, and execute the following code:

```{r}
#| eval = FALSE

rsconnect::setAccountInfo(name ='grapph',
                          token = my_token,
                          secret = my_secret)

rsconnect::deployApp(account = 'grapph')
```

I usually save this code in a non-git tracked file called 'shinyapps.R'

Be sure to set the name to 'grapph' so that the app is linked to the correct account. You may need to be added to the grapph account on shinyapps.io to have access. Note: for the CF related apps linked to Rhonda's R01, this name is 'medmonitoring'.

When updating and overwriting a previous app, rsconnect will ask if you want to overwrite the app currently hosted, where you can confirm your url and enter 'y'.

The url of the app will be a composite one consisting of {name}.shinyapps.io/{parent folder of app}. In our case, grapph.shinyapps.io/codec_shiny. The easiest way to rename the app is by renaming the folder containing the app.R file.
